### PR TITLE
Router Gaurd corrected for ManagerView route 

### PR DESCRIPTION
**Pull request by vishavsingla**
ManagerView route was accessible without being invited

### CODE REVIEW

**Review by jvJUCA — CHANGES_REQUESTED** [review]
Don't working for me, please tell if need further configurations

**Comment by KarinePistili** [comment]
@vishav-singla will you be able to make the changes? If not we will asign it somebody else, so please ping us back ;)

**Comment by vishavsingla** [comment]
@KarinePistili  Yes, I will try to rectify it this weekend was busy from 2 weeks due to college examinations

**Comment by KarinePistili** [comment]
Thanks for the fast answer @vishavsingla !! Okay, I'll wait for you them! :muscle:

**Comment by jvJUCA** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
