### PR TITLE
Heuristics now being auto saved on tab change.

### LINKED ISSUE #376: [🐞 BUG]: Heuristics disappearing on tab change.
### Bug Description :
Suppose I am creating some heuristic and want to switch to some other tab(eg. Options tab in the video below), the heuristic just disappears. I think it may lead to some problem if someone is not aware of hitting the save button every time before changing the tab.

https://github.com/ruxailab/RUXAILAB/assets/107767172/a83a5a8e-56df-43e3-bcf9-822ec94247c8

### PR DESCRIPTION
**Pull request by RishabhJain0721**
Closes #376 

Earlier, while creating heuristics, if someone changed the tab without hitting save button, the data was vanishing. 
Now, whenever someone changes a tab, the heuristic first auto saves and then proceeds. 

Here is the video demonstration of the same :

https://github.com/ruxailab/RUXAILAB/assets/107767172/f067058a-1918-4a99-a10f-7ebfc000ec31

### CODE REVIEW

**Comment by RishabhJain0721** [comment]
@KarinePistili @jvJUCA Kindly have a look at the changes I made regarding the issue mentioned above.

**Review by jvJUCA — CHANGES_REQUESTED** [review]
Dear @RishabhJain0721,

Thank you for your pull request. However, I wanted to clarify the intended functionality. We aim to save modifications locally in the Vuex store upon tab changes, while actual database saving should only occur upon user clicking the "save" button. This maintains a user-friendly workflow where changes are reviewed before committing. Therefore, I kindly request adjusting the approach accordingly.
You can see the user unmoderated test for example to how to do, and the flow of the data save.

Best regards,
@jvJUCA

**Comment by RishabhJain0721** [comment]
Hey @jvJUCA 
Thank you for clarifying the intended functionality. I will be making the required changes.
Thank you.

**Comment by RishabhJain0721** [comment]
Hey @jvJUCA 
Should I use "Heuristic.js" file (path :  src/store/modules/Heuristic.js) for storing the Heuristics locally on Vuex store as I don't see any mutations already?

**Comment by jvJUCA** [comment]
@RishabhJain0721 i think the best way is verify how is used in user tests and copy the logic

**Comment by RishabhJain0721** [comment]
Alright thank you @jvJUCA . Will do the same.

**Comment by KarinePistili** [comment]
Issue was already complete on pull request https://github.com/ruxailab/RUXAILAB/pull/393

**Pull request closed without merging**
