### PR TITLE
feat: a global error handling model

### PR DESCRIPTION
**Pull request by Gaurav-Verma07**
Related issue: #335 

Create a global error handling model having following fields: 
- errorCode
- message

Used `vue-toastification` library to show error messages.
Implemented the error handling in **signin page** (signin() )

image

### CODE REVIEW

**Comment by Gaurav-Verma07** [comment]
Hii @jvJUCA , hope you're doing well!!!

Apologies for the late PR (I was having issues with my system).

I've created a globalErrorHandler component as discussed. 
The model contains 2 parameters {errorCode, message}
For now I've implemented it only **Auth.js/signin()** so that you can review the core functionality first.
If the errorModel is as per our expectations, I'll extend it to the whole codebase.

**Comment by Gaurav-Verma07** [comment]
Also, I'm getting this warning in the console... I'm trying but maybe you can help here :)

image

**Review by jvJUCA — COMMENTED** [review]
@Gaurav-Verma07 
Congratulations! 🎉 Your pull request has been accepted! Thank you for your valuable contribution.

Your changes have been merged successfully and will be included in the develop branch. Your effort in improving our project is greatly appreciated.

Thanks again for your contribution, and we look forward to your continued involvement in our project!

Best regards,
@jvJUCA

**Review by jvJUCA — APPROVED** [review]

**Comment by Gaurav-Verma07** [comment]
Hey @jvJUCA , 
I still have to add new **GlobalErrorHandler** at every place we use setError otherwise it may misbehave. 
For now, I had only included it for signin page errors.

Should I open a new issue to resolve this?

**Comment by jvJUCA** [comment]
> Hey @jvJUCA , I still have to add new **GlobalErrorHandler** at every place we use setError otherwise it may misbehave. For now, I had only included it for signin page errors.
> 
> Should I open a new issue to resolve this?

Yes, i think you will need to change the set errors around the code, can you create this issue?

**Comment by Gaurav-Verma07** [comment]
Create new Issue.. working on it

**Pull request merged**
