### PR TITLE
small typo fix At testAnswer

### PR DESCRIPTION
**Pull request by saltykheera**

### CODE REVIEW

**Review by jvJUCA — APPROVED** [review]

**Review by jvJUCA — CHANGES_REQUESTED** [review]
The text has been changed to use internationalization (i18n) for translation. Therefore, if you want to modify the text, you will need to do so in the i18n files.

**Comment by saltykheera** [comment]
> The text has been changed to use internationalization (i18n) for translation. Therefore, if you want to modify the text, you will need to do so in the i18n files.

@jvJUCA this page is in english no matter what language you use . i18n is not emplemented for this page 
image

**Comment by jvJUCA** [comment]
I think you have the old develop

**Comment by saltykheera** [comment]
> I think you have the old develop

i will check

**Pull request closed without merging**
