### PR TITLE
Dependabot Implemented for Automated Dependency Updates

### PR DESCRIPTION
**Pull request by RanitMukherjee**
Enable Dependabot:
- Go to your repository settings on GitHub.
- Navigate to the “Security & analysis” section.
- Enable Dependabot alerts and security updates.

Addresses Issue #377

### CODE REVIEW

**Comment by asr2003** [comment]
@RanitMukherjee I am working on it and almost done. Will raise a PR tommorow. I am bit busy in working on proposal

**Comment by asr2003** [comment]
It isn't good in open-source community to raise a PR that not assigned to you

**Comment by RanitMukherjee** [comment]
It is not uncommon for the first person to raise a PR or be assigned to an issue for repositories in open-source communities. However, as RUXAILAB follows the Assignee system, I apologize for any confusion. If you don't mind, we can co-author this PR.

**Comment by KarinePistili** [comment]
Merge already satisfied by https://github.com/ruxailab/RUXAILAB/pull/412

**Pull request closed without merging**
