### PR TITLE
Added i8n translation for Heuritsic Test Pages

### PR DESCRIPTION
**Pull request by BasmaElhoseny01**
Added i18n translation [English] with the tag [TODO] for the same objects in the other 3 language files. This will help in translation; just replace the [TODO] placeholder https://github.com/BasmaElhoseny01/RUXAILAB/blob/ce771c3930dcd54011c150c94b6d2d33d166b17e/src/locales/es.json#L187-L189

### Components Done:

1. WeightTable
2. HeuristicsSettings
3. HeuristicsOptions
4. EditHeuristicsTest
5. ReportView
6. FinalReportView
7. UnmoderatedCoopsView
8. TestView

### Components Pending:

1. HeuristicsTestAnswer https://github.com/BasmaElhoseny01/RUXAILAB/blob/ce771c3930dcd54011c150c94b6d2d33d166b17e/src/store/modules/Answer.js#L160-L189  --> This component has headers rendered from src\store\modules\Answer.js. We need to take text values from here and reuse them inside the Vue component itself to be able to use the translation module. A lot of refactoring will be done, which may cause other things to crash, so I will check with the one responsible for this part of the code.

### Outcome:

Pages listed above now have i18n feature for English + placeholders only to be translated for the other 3 languages.

### Next Steps:

1. Fix issue for HeuristicsTestAnswer Headers to be translated.
2. Open an issue for moderatedTest for translation.
3. Assign the translation for the languages to a new contributor who is eager to start contributing (A simple task).

### CODE REVIEW

**Comment by jvJUCA** [comment]
Please merge the latest changes from the develop branch into your branch and resolve any conflicts locally!

**Review by jvJUCA — CHANGES_REQUESTED** [review]
Please merge the latest changes from the develop branch into your branch and resolve any conflicts locally!

**Comment by BasmaElhoseny01** [comment]
I have Fixed Conflicts and merged latest changes in develop branch you can check it out @jvJUCA

**Review by jvJUCA — APPROVED** [review]
Ok Basma, Approved!!

**Pull request merged**
