### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jvJUCA**
English fix

### CODE REVIEW

**Comment by hillhack** [comment]
Hii, i m data science student and i like to contribute to this organization.

**Comment by akash8843** [comment]
Hello @KarinePistili, 

My name is Akash Shukla, and I’m an aspiring software engineer passionate about web development. I have hands-on experience with HTML, CSS, JavaScript, Bootstrap, and Node.js, and I’ve been actively learning through real-world projects. 

I’m really interested in contributing to the RUXAILAB project for GSoC 2025. However, I feel like I might be a bit late in starting my contributions, and I’m worried about catching up. 

Could you please guide me on how I can still contribute and where I should begin? I’m eager to learn, work hard, and make meaningful contributions to the project with your support. 

Looking forward to your response! 

Best,  
Akash Shukla

**Comment by elenamolero** [comment]
Dear RUXAILAB Team,

My name is Elena Molero, and I am excited to apply for the Google Summer of Code with your organization. I am an spanish final-year Computer Engineering student with a strong artistic vision and an extensive portfolio that combines technology and design.

As an active member of the Aula de Software Libre (Free Software Group) at the University of Córdoba (Spain), I have contributed both technically and artistically to various open-source projects and events, including SalmorejoTECH, one of our most recognized initiatives. My experience spans areas such as front-end development, UI/UX design, and creative programming, making me particularly interested in RUXAILAB’s mission to enhance remote usability testing with AI.

I would love to dedicate 350 hours to a project related to UX/UI, as this is an area I am deeply passionate about. However, I am open to contributing to any project where my skills can be useful. In fact, I have explored past project ideas and found some particularly exciting, such as facial recognition and emotion evaluation, which I would be eager to work on.

I would love to collaborate with your community, learn from your mentors, and contribute meaningfully to the project. I would love to discuss how my skills in Figma (I REALYY <3 FIGMA), html, css, JavaScript, Flutter, Python, C, C++, Java, React.js... can align with RUXAILAB’s goals.

Looking forward to hearing from you!

Best regards,
Elena :)

**Comment by AmenaSaher** [comment]
Hello! I'm Amena, a computer science graduate student. I'm excited to apply to gsoc 2025 for your organization. I'm proficient in HTML/CSS, JavaScript and Python. I love designing and aspire to work as a user experience designer and work on improving accessibility. I would love to contribute to your project!

**Comment by Anaidasiv** [comment]
Hello @KarinePistili,

I hope you're doing well.

I am Anaida Siv, a Master's graduate in Software Engineering from London with proficiency in full-stack development and Python automation testing using Selenium and Playwright. I have registered for GSoC 2025 and am particularly interested in the project "Enhancing Playwright Testing in RUXAILAB", as I am passionate about automation.

Additionally, I enjoy technical writing and documentation. My dissertation on creating an Operational Resilience Maturity Framework is set to be published as a white paper by WCIT this year.

I am really excited about the opportunity to contribute to this project.Looking forward to hearing from you.

Regards,
Anaida

**Comment by naohchan** [comment]
Hello! I’m Gerald Rodriguez, and I am currently pursuing an MSc in Computer Science at the University of Bristol in the road to the distinction mark. I have three years of experience in data analytics, reporting, and database management. My technical expertise includes JavaScript, JAVA, Python, C, Git, and software development, with a growing focus on systems programming and automation. In addition I have experienced been Discord Moderator Channel. so I think I'm a good fit for Integration of GitHub Actions with Discord Role Management (90h)

I am originally from Peru and now based in Bristol, UK. My motivation to participate in this project came from my passion for open-source software and my interest in contributing to a meaningful initiative, as I have been volunteering in full stack projects in and out of UK. I see this opportunity as a way to enhance my skills in software development while collaborating with an international community and by doing what I have always like, automate tasks and use Discord!

**Comment by Tenjin2** [comment]
hii @KarinePistili ,
I'm Dhruv Thakur, a B.Tech CSE student (2nd year) from India with a strong passion for web development and programming.
Tech Skills:
good in HTML, CSS, and JavaScript for frontend development.
Comfortable with Python.
Continuously learning and improving my skills to build great, impactful projects.
First-Time Contributor!
This is my first time contributing to open source, and I’m excited to learn, collaborate, and give my best to the community. Looking forward to making meaningful contributions!
 GitHub: https://github.com/Tenjin2
Let's build something great together! 😎

**Comment by louiseluli** [comment]
Hi all! 

I'm Louise - currently I'm studying a MSc in Artificial Intelligence at the University of Essex (UK) with a Chevening/Lemann Foundation Scholarship. 

My background is quite interdisciplinary. I'm from Brazil, lived in Poland for 8 years. My first degrees are in international relations and cultural studies, but I have had professional experiences in compliance and cybersecurity.
I am working on combining my diverse skills using AI, cybersecurity, and intersectionality—especially race, gender, sexuality, and human rights—to combat online harms against minorities. 
Right now, my thesis is shaping up around the use of AI-driven tools to identify, reduce, and prevent bias and discrimination in online content, particularly focusing on how marginalized communities interact with digital platforms.

While researching the opportunities with RUXAILAB, I found the "AI-Powered Accessibility Evaluation," because it directly complements my thesis and personal project, which aims to develop an app focused on minority protection online. I would love to contribute to the project while also learning from your experience in the area.

I'm really looking forward to learning more about the project itself and discuss about it, if possible. I am also open to explore other areas.

Thank you and I hope we can meet and collaborate.

Cheers,
Louise

**Comment by LoganSong02** [comment]
Hi @KarinePistili and RUXAILAB team,

I'm Yuhang (Logan) Song, a senior at the University of Southern California majoring in Computer Science. I'm passionate about building impactful solutions that combine software engineering with AI. I've interned at Tencent, worked as a Teaching Assistant for core CS courses at USC, and collaborated with the USC Institute for Creative Technologies to develop an AI-powered math education platform.

I'm proficient in Java, Python, JavaScript, HTML/CSS, React, Spring, MongoDB, MySQL, Redis, Firebase, AWS, and Docker, and I'm certified as an AWS Machine Learning Engineer – Associate.

I'm especially interested in the following GSoC 2025 projects: UI Layout Optimization for RUXAILAB (175h), Comparative Analysis and Fine-Tuning of Sentiment Models for Improved System Integration (175h), and Integration of GitHub Actions with Discord Role Management (90h).

With my background in frontend&backend development and experience with ML systems, I’m excited to explore how I can contribute meaningfully to your work. Looking forward to learning more and collaborating with the community!

Best,
Logan
Linkedin: https://www.linkedin.com/in/yuhang-song-71415b224/

**Comment by mayaa5a** [comment]
Hi everyone and @KarinePistili,

I'm Maya Ali, a second year Computer Science student at the University of Texas at Austin. I am interested in learning and contributing to technology, software development, and open-source collaboration. I have experience in HTML, CSS, Java, JavaScript, and Python.

I am very excited to meet all of you and potentially join the team!

Currently, I’m exploring the repository, familiarizing myself with the codebase, and making small contributions to get started. I’m particularly interested in the UI Layout Optimization for RUXAILAB project, and I look forward to learning from the community and while making meaningful contributions.

**Comment by AlwinXue** [comment]
Hi everyone,

I'm Yukai Xue, a master's student in Computer Science at New York University (NYU). I’m passionate about software infrastructure, developer tools, and open-source collaboration. Over the past few years, I’ve completed six software engineering internships at companies including Snowflake, Activision Blizzard, and Philips, focusing on CI/CD automation, monitoring, SonarQube integration, and scalable backend systems.

I’m currently preparing a GSoC proposal for Uramaki LAB, focused on Automating Issue Creation from SonarQube in CI/CD Pipelines. I have previous hands-on experience with SonarQube, GitHub Actions, Jenkins, and Terraform, and I’m excited to apply these skills in an open-source context.

Looking forward to learning from the community and contributing to something impactful!

GitHub: https://github.com/AlwinXue
LinkedIn: https://linkedin.com/in/yukai-xue

**Pull request merged**
