### PR TITLE
fix(heuristics): heuristic items are not properly aligned on vertical…  ISSUE #480

### PR DESCRIPTION
**Pull request by saltykheera**
… axis #480

issue mentioned by marc about wrong align of icon : mdi-chevron-right
image

### CODE REVIEW

**Comment by marcgc21** [comment]
Hi @saltykheera! Looks nice but might be possible reduce a little big the row size? Can you tell me right now wich is his height?

**Comment by saltykheera** [comment]
@marcgc21 current height is 56px
image

**Comment by saltykheera** [comment]
@marcgc21 check the improved commit it has 40px size and it look decent
image

**Review by jvJUCA — CHANGES_REQUESTED** [review]
I agree with the proposed fix. However, is there a way to implement this design change responsively? Hardcoding the height to 40px seems incorrect to me.

**Review by jvJUCA — APPROVED** [review]
Your changes have been merged successfully and will be included in the develop branch. Your effort in improving our project is greatly appreciated.

**Pull request merged**
