### PR TITLE
Translate JSON keys and values into Hindi

### PR DESCRIPTION
**Pull request by TheMohit2003**
This PR introduces complete Hindi translations for the keys and values within the JSON file, enhancing accessibility for Hindi-speaking users.

### CODE REVIEW

**Comment by TheMohit2003** [comment]
I'm also prepared to add German translations in a separate PR if that would be helpful for the project.

**Comment by TheMohit2003** [comment]
Hey @jvJUCA , I will do the changes .  In the switch, do you want hindi option to be in English script or hindi script?

**Comment by jvJUCA** [comment]
> Hey @jvJUCA , I will do the changes . In the switch, do you want hindi option to be in English script or hindi script?

Hey @TheMohit2003,

Thanks for your quick response. We would prefer the Hindi option to be in Hindi script in the language switch. This will ensure consistency with the language representation throughout the application.

Let me know if you have any further questions or need clarification.

Best regards,
@jvJUCA

**Comment by TheMohit2003** [comment]
The latest commit adds hindi to language change option .
```javascript
{ label: 'हिन्दी', value: 'hi'}
```
@jvJUCA  , any other changes ?

**Review by jvJUCA — APPROVED** [review]
Dear @TheMohit2003 ,

Congratulations! 🎉 Your pull request has been accepted! Thank you for your valuable contribution.
Your changes have been merged successfully and will be included in the develop branch. Your effort in improving our project is greatly appreciated.

Thanks again for your contribution, and we look forward to your continued involvement in our project!

Best regards,
@jvJUCA

**Pull request merged**
