### PR TITLE
Added vscode extension recommendation

### PR DESCRIPTION
**Pull request by TheMohit2003**
### Description

This PR introduces a `.vscode/extensions.json` file to the project, aimed at recommending the Vetur extension for Visual Studio Code users working on this Vue.js project. It addresses #343 
### Changes

- Created a `.vscode` directory at the root of the project (if it didn't already exist).
- Added an `extensions.json` file within the `.vscode` directory.
- Specified `"octref.vetur"` as a recommended extension in `extensions.json`, encouraging contributors to install Vetur for enhanced Vue.js development support in VS Code.

### Additional Notes

- The extension that is recommeded supports vue version 2 .
- The official docs recommend volar ( vue 3 ) which even works for vue 2 but for vue vesions lesser than 2.6.14 , some configs need to change 
image
- [Extension page](https://marketplace.visualstudio.com/items?itemName=Vue.volar)

### CODE REVIEW

**Comment by TheMohit2003** [comment]
If needed I will change the vue extension version from ve

**Review by jvJUCA — CHANGES_REQUESTED** [review]
Set Default linter as Prettier too, please!

**Comment by TheMohit2003** [comment]
@jvJUCA , sure

**Comment by TheMohit2003** [comment]
I have set prettier as the default formatter using settings.json file , do you want me to remove extensions recommendation then ?

**Comment by TheMohit2003** [comment]
Changes made in the latest commit :
- Added prettier as the default formatter 
- Removed the extension recommnedation

**Review by jvJUCA — APPROVED** [review]

**Comment by jvJUCA** [comment]
Congratulations! 🎉 Your pull request has been accepted! Thank you for your valuable contribution.

Your changes have been merged successfully and will be included in the develop branch. Your effort in improving our project is greatly appreciated.

Thanks again for your contribution, and we look forward to your continued involvement in our project!

Best regards,
@jvJUCA

**Pull request merged**
