### PR TITLE
Add Support for Dependabot for Automated Dependency Update

### PR DESCRIPTION
**Pull request by asr2003**
This PR Fixes:

-  #377 

**Motivation:**
The motivation behind this feature request is to ensure that our project's dependencies are regularly updated to include security patches, bug fixes, and new features. Dependabot will automate the process of monitoring and updating dependencies, reducing the manual effort required to keep our project up-to-date.

**Feature:**

1. Dependabot will periodically check for updates to our project's dependencies.
2. When updates are available, Dependabot will create pull requests to update the dependencies in our project.
3. We can review and merge these pull requests to incorporate the latest dependency versions into our project.

### CODE REVIEW

**Comment by asr2003** [comment]
@KarinePistili PTAL and review it

**Comment by varshith257** [comment]
@KarinePistili @FernandaCasali  Any update here?

**Review by varshith257 — APPROVED** [review]
@jvJUCA @KarinePistili  LGTM

**Review by KarinePistili — APPROVED** [review]

**Comment by KarinePistili** [comment]
Thank you for the contribution!

**Comment by asr2003** [comment]
> Thank you for the contribution!

Will be there always to enhance our codebase :)

**Pull request merged**
