### PR TITLE
Enhancement: Refactor CreateBlankView.vue into Reusable Components

### PR DESCRIPTION
**Pull request by sushant4612**
Description:
This pull request resolves issue #347 by breaking down the CreateBlankView.vue file into smaller, reusable components. This approach improves code organization and maintainability, making it easier to manage and understand.

Changes Made:
Introduced three new components: UserTestDialog, TestCreationDialog, and CardComponent. These components modularize the content of CreateBlankView.vue, enhancing reusability and maintainability.

### CODE REVIEW

**Comment by sushant4612** [comment]
Hey @jvJUCA , whenever you have time, kindly review my pull request and let me know if any changes are required.

Thank you!

**Comment by KarinePistili** [comment]
Hello @sushant4612 ! Sorry for taking long to review! It looks great the components, but in the previous weeks we had some modifications on them which caused conflicts.

Could you update the components you created with latest code on develop to solve this conflicts? We would like to maintain the new features we added, but use the generic .vue you made.

Thank you for contributing!

**Review by KarinePistili — CHANGES_REQUESTED** [review]
Could you update the components you created with latest code on develop to solve this conflicts? We would like to maintain the new features we added, but use the modularized .vue you made.

**Comment by sushant4612** [comment]
Sorry for the delay in replying @KarinePistili. I've been busy with my practical papers, which is why I haven't been so active. I'll look at the changes you mentioned as soon as possible.

**Comment by KarinePistili** [comment]
Okay, thanks!

**Comment by sushant4612** [comment]
Sorry for the late response actually I was busy with my end-semester exams just now i saw the mail and It feels great when you invest a lot of time and your pull request gets accepted. 

I'm looking forward to making more meaningful contributions.

**Pull request merged**
