### PR TITLE
[E2E TESTS] Generate auth utils + auth test + heuristic test

### PR DESCRIPTION
**Pull request by sergiobeltranguerrero**
This pull request introduces several improvements and additions to the application’s authentication and testing system. The changes made are detailed below:

- Authentication Utilities: Utilities have been developed to handle common authentication operations, including login, signup, and user deletion. This simplifies and speeds up the creation of tests, avoiding the repetition of steps across different test suites.

- e2e Tests for Registration and Login: End-to-end (e2e) tests have been implemented for the main use cases of registering and logging in a user.

- e2e Tests for Heuristic Testing: Additionally, an e2e test specifically designed to evaluate a heuristic test has been added.

A video of the execution is attached.

- GUI video: https://drive.google.com/file/d/1HHAZofUuRME2bbSQ6x1UdmgUjVioymef/view?usp=sharing
- CLI video: https://drive.google.com/file/d/1Ig-wFTQIzlNvoGwmUvPg_77wyOMw8hxv/view?usp=sharing

> Please note that 'npm run serve', 'npm run cypress:open' and 'firebase emulators:start' must be executed beforehand.

### CODE REVIEW

**Comment by sergiobeltranguerrero** [comment]
@KarinePistili this pull request is ready to solve 😄

**Comment by JulioManoel** [comment]
@sergiobeltranguerrero When I run the Webpack Compilation Error error
image

**Comment by sergiobeltranguerrero** [comment]
@JulioManoel  You can try running npm install, it may be that the 'package-lock.json' file is not up to date.

**Comment by sergiobeltranguerrero** [comment]
@HuYou can try running npm install, it may be that the 'package-lock.json' file is not up to date.

**Pull request merged**
